---
title: "Course 2 Section 4.6 - REGRESSION TREES"
author: "Jiaying Wu"
date: "17/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 5,
                      fig.height = 4,
                      fig.align = "center")
```

### Give it a go!

Continue to develop your skills and understanding of regression trees by making your way through this exercise.

For this exercise use the following data set.

```{r}
library(tibble)
d <- tibble(x=c(1.5, 2.8, 4.1, 2.0, 5.2), y=c(6.2, 4.8, 5.1, 7.1, 3.7))
d
```

#### Q1.Sketch the data on a piece of paper. How many possible splits are there in this data?

```{r}
p <- ncol(d)
n <- nrow(d)
(p-1)*(n-1)
```


#### Q2.Use the function provided in this step to compute the ANOVA criterion for each split.

```{r}
SST <- sum((d$y - mean(d$y))^2)
SSG <- NA

for(i in 1:(n-1)){
  SSG1 <- sum((d$y[1:i] - mean(d$y[1:i]))^2)
  SSG2 <- sum((d$y[-c(1:i)] - mean(d$y[-c(1:i)]))^2)
  SSG[i] <- SSG1 + SSG2
  message("i=", i, ", SSG1=", SSG1, ", SSG2=", SSG2, ", SSG1+SSG2=", SSG[i], ", ANOVA=", SST-SSG[i])
}
SST - SSG
```

