---
output: github_document
---

```{r setup, include = FALSE}
# The README markdown generate by this rmd file, please edit the content within this R markdown.
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  fig.path = "image/",
  fig.align = "center",
  echo = FALSE
)
```

# Sample Answer Code for Data Science: Data-Driven Decision Making

### Course 1: Data Wrangling and Workflow

#### Week 2: PLOTTING DATA, TIDYING YOUR DATA AND USING WRANGLING VERBS

- `C1S2_03.Rmd`: Sample answer code for Course 1 Step 2.3: `THE GRAMMAR OF GRAPHICS`

- `C1S2_08.Rmd`: Sample answer code for Course 1 Step 2.8: `YOUR TURN`

- `C1S2_14.Rmd`: Sample answer code for Course 1 Step 2.14: `YOUR TURN`

- `C1S2_17.Rmd`: Sample answer code for Course 1 Step 2.17: `FILTER`

- `C1S2_19.Rmd`: Sample answer code for Course 1 Step 2.19: `MUTATE`

- `C1S2_20.Rmd`: Sample answer code for Course 1 Step 2.20: `SUMMARISE: COMPUTE SUMMARIES`

- `C1S2_22.Rmd`: Sample answer code for Course 1 Step 2.22: `ARRANGE: ORDERING ROWS`

- `C1S2_24.Rmd`: Sample answer code for Course 1 Step 2.24: `YOUR TURN`

#### Week 3: HARVESTING DATA, VISUAL ANALYTICS, AND THE ROLE OF DATA VISUALISATION

- `C1S3_04.Rmd`: Sample answer code for Course 1 Step 3.4: `AESTHETICS`

- `C1S3_11.Rmd`: Sample answer code for Course 1 Step 3.11: `READING AND WRITING PROPRIETARY FORMATS`

- `C1S3_12.Rmd`: Sample answer code for Course 1 Step 3.12: `WEB SCRAPING`

- `C1S3_13.Rmd`: Sample answer code for Course 1 Step 3.13: `READING AND WRITING JSON FILES`

- `C1S3_15.Rmd`: Sample answer code for Course 1 Step 3.15: `YOUR TURN`


### Course 2: Modelling and Visualisation

#### Week 1: DATA WRANGLING IN DETAIL

- `C2S1_07.Rmd`: Sample answer code for Course 2 Step 1.7: `RELATIONAL DATA`

- `C2S1_09.Rmd`: Sample answer code for Course 2 Step 1.9: `JOINS`

- `C2S1_11.Rmd`: Sample answer code for Course 2 Step 1.11: `YOUR TURN`

- `C2S1_13.Rmd`: Sample answer code for Course 2 Step 1.13: `MISSING VALUES`

- `C2S1_15.Rmd`: Sample answer code for Course 2 Step 1.15: `DEALING WITH MISSING DATA`

- `C2S1_17.Rmd`: Sample answer code for Course 2 Step 1.17: `YOUR TURN`

#### Week 2: TEMPORAL AND SPATIAL DATA

- `C2S2_05.Rmd`: Sample answer code for Course 2 Step 2.5: `WORKING WITH DATES AND TIMES`

- `C2S2_08.Rmd`: Sample answer code for Course 2 Step 2.8: `YOUR TURN`

- `C2S2_10.Rmd`: Sample answer code for Course 2 Step 2.10: `SPATIAL POINT DATA`

- `C2S2_13.Rmd`: Sample answer code for Course 2 Step 2.13: `YOUR TURN`

